### ISSUE TITLE
The mod should be able to request a specific seed from the API

### ISSUE THREAD

**Issue by Sgt-Imalas** [barratt/mapsnotincluded.org#43]
When set to Random clusters, the mod should be able to fetch a specific seed from the API

**Comment by barratt** [comment]
We can create a 'queue' table in PostgreSQL where when you request /worker/seed it will automatically return just one world and set the state to 'processing' so that we dont get two people generating the same world, additionally we can have a worker that runs every few minutes to check how long generation is taking, if it takes over x minutes for that worker to generate the seed then we return it back to the queue as that mod might have crashed

**Comment by Sgt-Imalas** [comment]
the mod side request must contain a list of active (and owned) dlcs, so they can only receive seeds they can actually run
