### ISSUE TITLE
[MOD] Capture data for preview map (biome overview)

### ISSUE THREAD

**Issue by StefanOltmann** [barratt/mapsnotincluded.org#5]
The original TNI had a biome map that looked like this:

![image](https://github.com/user-attachments/assets/ab203485-2130-4ae2-9c16-a61a4e314f7c)

We already have the POI locations, but the mod also needs to extract the tile types and merge these locations into curves.

From what we now is that the original TNI mod has a logic to create a SVG out of the tiles biome information. We need to re-create this logic.

**Comment by blake-sc** [comment]
It seems the biome data is straightforward enough in the saves, found under the path:
`save.gameData.worldDetail.overworldCells`

If I'm understanding what I'm  seeing correctly, for a typical map it's about 150 polygons each with an array of 4 or more vertexes and a bunch of tags one of which is the biome type and a zoneType integer which seems to be the biome and seems to always be the same across saves, e.g. zoneType 0 is FrozenWastes, 3 is Sandstone, 7 is Space... So all we really need to pull out from there, would seem to be the vertices and the zoneType.

It's probably worth applying some thought on how best to represent this data in a database and dumps, it's a fair bit of data. I don't see any good reason why this data would need to be indexed, so it could/should be some kind of blob.

SVG polygons are actually a fairly compact representation of a polygon and it's embarrassingly easy to go from the vertices data to SVG polygons, I did a quick proof of concept (coded in python sorry, my JS is very rusty and I couldn't be bothered) and generated a biome SVG from a random base game save file:

![biomes](https://github.com/user-attachments/assets/3c220fc8-187c-4f7d-9d8a-bcddd847363d)

For this save file, the basic SVG of the biome polygons comes to about 9kb, 2kb when zipped, which is a pleasingly trifling amount of data.

To be honest, I think that storing the SVG polygons in the database (as a big blob) is probably a good approach, I can't really think of a more compact representation particularly if compression is involved, like the scheme I used, each biome is represented like this:
```
<polygon points="28,363 17,353 0,353 0,384 26,384" class="zone5" />
<polygon points="17,353 29,329 24,320 0,320 0,353" class="zone6" />
<polygon points="30,306 18,289 0,289 0,320 24,320" class="zone2" />

...
```

And that's already pretty compact.

From there, the biome polygons would have to be integrated with the POI images to form the map. The approach which would seem obvious to me, would be to have the POIs as an entirely separate overlay on top of the biome SVG, perhaps even as HTML elements with absolute positioning.

Since I don't have much of the stack working at the moment, I didn't feel particularly inclined to try and implement the proper extraction logic.

**Comment by StefanOltmann** [comment]
@blake-sc Thank you, that looks promising.

Could you share the code you used?

Since some information can't be extracted from save files, we use a world generation data collection mod (written by SGT_Imalas), which is included in the repo.

The mod is written in C# because Oxygen Not Included is a Unity game.
We'll need to translate your code to C# to integrate it.

For first-time setup with an ONI mod, the easiest approach is to check out the original repository of the mod. SGT_Imalas has included setup automation, which simplifies the process: https://github.com/Sgt-Imalas/Sgt_Imalas-Oni-Mods

I can share you the actual URL and API key when you're ready.

**Comment by blake-sc** [comment]
I didn't have to do anything in C# land as it seems all required information is already in the save files, except possibly what zoneType refers to - the biome IS listed in the tags, but the tags don't seem to appear in any particular order, so which tag is referring to the biome type is not obvious, also perhaps the color could be available, as biomes do seem to have some kind of color associated with them in-game.

Basically to summarize what I did, manually using oniSaveParser in Node REPL, I  dumped `save.gameData.worldDetail.overworldCells` as JSON.

I then parsed that in Python, which should be pretty trivial to translate into JS:

```
import json

with open('biomes.json') as f:
    biomes = json.load(f)

# hardcore height and width, this is trivially pulled from save I just didn't include it in the JSON dump
height = 384
width = 256

polys = []

for biome in biomes:
    zoneType = biome['zoneType']
    vertices = biome['poly']['vertices']
    points = ' '.join(['{:0.0f},{:0.0f}'.format(vert['x'], height - vert['y']) for vert in vertices])
    poly = f'<polygon points="{points}" class="zone{zoneType}" />'
    polys.append(poly)

poly_string = ''.join(polys)
```

That's pretty much it for getting the blob of SVG that could be committed to a database.

Then I stuffed the poly_string into a SVG with a stylesheet, the CSS I used is this:
```
<style>
        polygon {
            stroke-width: 0.5;
        }
        .zone0 {
            /* FrozenWastes */
            fill: cyan;
            stroke: cyan;
        }
        .zone2 {
            /* BoggyMarsh */
            fill: green;
            stroke: green;
        }
        .zone3 {
            /* Sandstone */
            fill: yellow;
            stroke: yellow;
        }
        .zone4 {
            /* ToxicJungle */
            fill: purple;
            stroke: purple;
        }
        .zone5 {
            /* MagmaCore */
            fill: red;
            stroke: red;
        }
        .zone6 {
            /* OilField */
            fill: saddlebrown;
            stroke: saddlebrown;
        }
        .zone7 {
            /* Space */
            fill: black;
            stroke: black;
        }
        .zone8 {
            /* Ocean */
            fill: seashell;
            stroke: seashell;
        }
    </style>```

We *might* want to try and pull that out of C# land, though perhaps better to not automate what can be hardcoded manually in half an hour? Anyway, it's well beyond my current capabilities to work with ONI mods, I've read the decompiled code a bit but have never worked with a mod and don't know the toolchain.

Then finally stuffed these things in a SVG template:
```
<svg height="{height*2}" width="{width*2}" viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg">
    {styleSheet}
    <g>
    {poly_string}
    </g>
</svg>
```

**Comment by StefanOltmann** [comment]
Resolved. :)

**Comment by StefanOltmann** [comment]
@blake-sc Using my tech (SKIA) this kind of SVG unfortunately renders to just a black image. It seems not to be standard compliant. Only after I re-save it with Affinity Designer it works?

Could you provide us code to generate a SVG like this?

![corrected_by_affinity.svg](https://github.com/user-attachments/assets/badfa939-ac33-47fe-9458-85ac5851a9e2)
